# Generated by Django 5.2 on 2025-04-19 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('apiFilme_id', models.TextField()),
                ('comentario_texto', models.TextField()),
                ('comentario_data', models.DateField(auto_now_add=True)),
                ('comentario_IMDB', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
