# Generated by Django 5.2 on 2025-04-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cartFilmes',
            fields=[
                ('cartFilmes_id', models.AutoField(primary_key=True, serialize=False)),
                ('apiFilme_id', models.TextField()),
                ('cartFilmes_genero', models.TextField()),
                ('cartFilmes_img', models.TextField()),
                ('cartFilmes_title', models.TextField()),
                ('cartFilmes_IMDB', models.BooleanField()),
                ('cartFilmes_data', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteracao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
